### ISSUE TITLE
Use the mempool.space API to search for Lightning nodes

### ISSUE THREAD

**Issue by fiatjaf** [nbd-wtf/obw#10]
Is this a good idea?

**Comment by Darth-Coin** [comment]
Yes. But it should have a filter or something, for those nodes that are "friendly" with "private" channels like OBW is using.
Some routing nodes, for some reasons, do not want private channels with them, so they will close these "not profitable" private channels with mobile wallets.

Will be cool to have like a "community list" verified list of good nodes with who you can open a channel using your mobile wallet. Noobs that don't know the history of routing nodes could open channels with some random nodes from the LN explorer and could end up using a bad one, that is not even capable to route his payments.

We need a curated list, where OBW users can vouch for those nodes that being good for using in a mobile node.

**Comment by fiatjaf** [comment]
Good points.

**Comment by fiatjaf** [comment]
Better use a list of nodes that are friendly to mobile wallets instead, like https://github.com/hsjoberg/blixt-wallet/issues/1033
