### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by agustinpfs** [nbd-wtf/obw#15]
In "Paid Lightning Channel providers" the links to "Zero Fee Routing" and "BlockTank" point to a 404 page. Github link too.

**Comment by Gravity2106** [comment]
> In "Paid Lightning Channel providers" the links to "Zero Fee Routing" and "BlockTank" point to a 404 page. Github link too.

Update your app

**Comment by agustinpfs** [comment]
Solved! Thanks
