### ISSUE TITLE
Channel open stuck as pending

### ISSUE THREAD

**Issue by senf42** [nbd-wtf/obw#19]
I initiated a channel open yesterday, and it still shows as "Opening..." in the channel list today. The funding txid from Share Lightning Channel details does not appear in the mempool/block explorers. The sat balance also seems to be reflected in both Lightning and Bitcoin on the main screen.

**Comment by senf42** [comment]
Good to know! My phone says the app version is 0.1.8, so it looks like I installed the first release and then upgraded to this. It looks like I last sent an on-chain transaction on 8 October, last received an on-chain transaction on 5 November. I do have that first channel open and working correctly. Will that carry over if I restore from the seed phrase plus the local channel backup, or will that local channel backup have issues?

**Comment by fiatjaf** [comment]
Well, so far there hasn't been any issues with the local channel backup and there is no reason for any issue since that part of the code didn't change at all from SBW.

But just in case I would rather ask you to first restore on a different phone with just the seed (no channel backup) and check if the onchain transactions show up correctly there.

**Comment by senf42** [comment]
Restoring with the seed phrase and no channel backup shows the same seven on-chain transactions on the new phone as the old phone. The total Bitcoin balance shown on each is different by about 1.1M sats, but the new phone's lower balance appears to be correct based on the history of on-chain transactions. The one open channel's balance on my existing phone is within about 50k sats of the 1.1M sat difference, if that's not a coincidence.

**Comment by agustinpfs** [comment]
Same issue. 24 hours ago I opened a channel and it's still "opening..." I have the latest version installed.

**Comment by fiatjaf** [comment]
@agustinpfs if you don't have any other normal channels can you wipe out your app data and recover from the seed? Or recover in another phone and check if the UTXOs match?

**Comment by agustinpfs** [comment]
@fiatjaf Ok. I just recovered from the seed on another phone and the UTXOS match, are the same. I did the recovery only from the seed (without the backup file of the channels)

**Comment by fiatjaf** [comment]
Hmm, then the channel open failed for some other reason. I must make it show that error message instead of just assuming the channel was created and waiting for it forever.

**Comment by agustinpfs** [comment]
I have tried to create channels with multiple nodes but have not been successful. In those channels it showed me an error message, but the message is trim and the cause cannot be read. The only one that allowed me to create a channel was "1ML.com node ALPHA" and it is the same one that was left waiting in "opening..."

**Comment by senf42** [comment]
@fiatjaf Should I restore with the channel backup as well now? Will that carry the "bad" channel into the new setup?

**Comment by fiatjaf** [comment]
No, the bad channel doesn't exist. Maybe you should verify that first. Long-press on it and share the channel data. There will be a `funding tx` in there, which you can paste on https://mempool.space/ and check if it exists. It probably won't.

**Comment by fiatjaf** [comment]
If you are going to restore the channel backup on another device make sure you will not open the app on the first device ever again or will erase it. If you have the same channel in two devices that **will cause a penalty transaction** and you'll lose all the funds in the channel.

**Comment by senf42** [comment]
I wiped the data for the app on my phone and restored with the channel backup and seed phrase, and it still shows the "bad" channel with a status of "Opening...", fyi (the funding transaction indeed does not show up in the mempool when I search for it). Whenever the mempool is empty again I'll close my one actual channel and then do a restore with just the seed phrase before opening channels again.

**Comment by senf42** [comment]
I closed the other active channel, wiped everything, and restored with only seed phrase. I opened a new channel that worked great for a couple days, had a few days where it wouldn't connect for some reason, but now has been rock solid for a couple weeks.

**Comment by fiatjaf** [comment]
Thank you for your feedback and patience, we're going to improve these things and make it more rock solid.
