### ISSUE TITLE
Improve project's searchability and discoverability

### ISSUE THREAD

**Issue by dtonon** [nbd-wtf/obw#30]
Currently is not so easy to find OBW using a search engine; "obw" and "open bitcoin wallet" usually bring the user to other resources. These are just some suggestions aimed to improve OBW searchability and discoverability:

* Change the repo name to "obw-open-bitcoin-wallet": this wil promote the keyword "(open) bitcoin wallet"; it is a competitive key of course, but why not try? Github manages trasparently the redirects (301), so no problem for the old links around.

* Change the repo description to "Open Bitcon Wallet (OBW) is a lightweight Android Bitcoin and Lightning wallet": this string is used in the html <title> and Open Graph tags, so it is picked up in a lot of contexts.

* Update the readme to increase keywords frequency, as per my pull request: https://github.com/nbd-wtf/obw/pull/29

This improvents should works nicely non only for the mainstream search engines but a wider search context, starting from the internal Github search, and have effect on the repo accessibility/usability too.

**Comment by fiatjaf** [comment]
Thank you very much, good suggestions. I've merged your PR and changed the description, also added some GitHub tags (suggestions on these accepted too). The repo name change I can't make because that would be too ugly and I wouldn't be able to live with it.

**Comment by dtonon** [comment]
Thank you!

> The repo name change I can't make because that would be too ugly and I wouldn't be able to live with it.

I agree, perhaps a too far step 😅👍
