### ISSUE TITLE
[BUG] Backup channels is not triggered

### ISSUE THREAD

**Issue by Darth-Coin** [nbd-wtf/obw#35]
### Description
The function to save a channels backup is not doing anything.

OBW vers. 0.2.0-11
Android 8.1 and Android 11, 12

### Actual behavior
![image](https://user-images.githubusercontent.com/56997124/209393310-8ff33e25-a415-4cfb-ae58-32132e300471.png)

In SBW, when you click on the option "Local channel backup is enabled" it trigger a channels backup file into your "downloads" folder on the device.
In OBW is NOT doing anything, it just open the app details.
So right now with this version, IT IS NOT POSSIBLE TO BACKUP AND RESTORE a OBW wallet if something bad could happen.
I discovered this bug when I tried to do a full backup / restore because of the issue #34 (gossip do not sync correctly).

### Expected behavior
The click on the backup option should popup a file explorer modal to choose where the file should be saved.
Or just a simple button that will save the backup file and a simple message like "file saved" if is success.

**Comment by dolcalmi** [comment]
I can confirm the 2 bugs. I know 3 other people having the `"channel sync is not finished"` issue even with v0.1.6, the "solution" was to restore the backup (although now there is no backup). Maybe the easiest solution is to have a couple of options to force a backup or channel sync.
