### ISSUE TITLE
SQLite database corrupt exception

### ISSUE THREAD

**Issue by dolcalmi** [nbd-wtf/obw#39]
Getting the next error after tap create wallet button (initial setup),

any clue how to solve it? (first time it happens)

![image](https://user-images.githubusercontent.com/2079600/212746475-fa8559f9-48a8-48fb-8356-20234f8bb482.png)

**Comment by fiatjaf** [comment]
I don't know, that looks like something on your phone blocking the creation of the database. Maybe you have to give permissions manually or something like that?

**Comment by acurious** [comment]
Get the same error on two Samsung phones with Android 10. Giving permissions manually don't help. SBW works fine, OBW returns the error. No error on Oneplus phone with Android 10.
